-- Add agreement_number to contracts for email intake matching (Signal 2)
-- Deferred from ADR 20260225095833-email-intake-matching-and-processing.md
--
-- agreement_number is auto-generated by the backend on confirm.
-- Format: LKH-{year}-{sequential} (e.g. LKH-2025-1, LKH-2025-42).
-- Unique per user per year via the constraint below.

ALTER TABLE contracts ADD COLUMN agreement_number TEXT;
ALTER TABLE contracts ADD CONSTRAINT contracts_user_agreement_unique UNIQUE (user_id, agreement_number);
